services:

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/novo-site
    networks:
      - backend

networks:
  backend:
    driver: bridge